#Jekyll configuration
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Ontology-Driven Conceptual Modelling of Digital Twins (ODCM-DT 2021)
description: In conjunction with Semantics 2021

#theme: jekyll-theme-cayman
